using System.Globalization;

using UnityEngine;

namespace TexturePainter
{
    public static partial class Utils
    {
#if UNITY_EDITOR
        public static string NameThatColor(Color color)
        {
            (int r, int g, int b) rgb = (
                Mathf.RoundToInt(color.r * 255),
                Mathf.RoundToInt(color.g * 255),
                Mathf.RoundToInt(color.b * 255)
            );

            var hexColor = GetHexColor(rgb);

            var r = rgb.r;
            var g = rgb.g;
            var b = rgb.b;

            var hsl = GetHSL(rgb);

            var h = hsl.h;
            var s = hsl.s;
            var l = hsl.l;

            int index = -1;
            float currentDiff = -1;

            float diff;

            var length = colorNameMap.GetLength(0);
            for (var i = 0; i < length; i++)
            {
                if (hexColor == colorNameMap[i][0])
                    return colorNameMap[i][1];

                rgb = GetRGB(colorNameMap[i][0]);
                hsl = GetHSL(rgb);

                diff = Mathf.Pow(r - rgb.r, 2) + Mathf.Pow(g - rgb.g, 2) + Mathf.Pow(b - rgb.b, 2)
                     + Mathf.Pow(h - hsl.h, 2) + Mathf.Pow(s - hsl.s, 2) + Mathf.Pow(l - hsl.l, 2) * 2;

                if (currentDiff < 0 || currentDiff > diff)
                {
                    currentDiff = diff;
                    index = i;
                }
            }

            return index < 0 ? "Unknown" : colorNameMap[index][1];
        }

        static string GetHexColor((int r, int g, int b) color)
        {
            return color.r.ToString("X2") + color.g.ToString("X2") + color.b.ToString("X2");
        }

        static (int r, int g, int b) GetRGB(string color)
        {
            return (
                int.Parse(color[0..2], NumberStyles.HexNumber),
                int.Parse(color[2..4], NumberStyles.HexNumber),
                int.Parse(color[4..6], NumberStyles.HexNumber)
            );
        }

        static (int h, int s, int l) GetHSL((int r, int g, int b) rgb)
        {
            var r = rgb.r;
            var g = rgb.g;
            var b = rgb.b;

            var min = Mathf.Min(r, g, b);
            var max = Mathf.Max(r, g, b);
            var delta = max - min;

            float l = (min + max) / 2f;

            float s = 0f;
            if (l > 0 && l < 1)
                s = delta / (l < 0.5 ? (2 * l) : (2 - 2 * l));

            float h = 0f;
            if (delta > 0)
            {
                if (max == r && max != g) h += (g - b) / delta;
                if (max == g && max != b) h += (2 + (b - r) / delta);
                if (max == b && max != r) h += (4 + (r - g) / delta);
                h /= 6;
            }

            return (
                Mathf.Clamp(Mathf.RoundToInt(h * 255), 0, 255),
                Mathf.Clamp(Mathf.RoundToInt(s * 255), 0, 255),
                Mathf.Clamp(Mathf.RoundToInt(l * 255), 0, 255)
            );
        }

        static readonly string[][] colorNameMap = new string[][]
        {
            new[] { "000000", "Black" },
            new[] { "000080", "Navy Blue" },
            new[] { "0000C8", "Dark Blue" },
            new[] { "0000FF", "Blue" },
            new[] { "000741", "Stratos" },
            new[] { "001B1C", "Swamp" },
            new[] { "002387", "Resolution Blue" },
            new[] { "002900", "Deep Fir" },
            new[] { "002E20", "Burnham" },
            new[] { "002FA7", "International Klein Blue" },
            new[] { "003153", "Prussian Blue" },
            new[] { "003366", "Midnight Blue" },
            new[] { "003399", "Smalt" },
            new[] { "003532", "Deep Teal" },
            new[] { "003E40", "Cyprus" },
            new[] { "004620", "Kaitoke Green" },
            new[] { "0047AB", "Cobalt" },
            new[] { "004816", "Crusoe" },
            new[] { "004950", "Sherpa Blue" },
            new[] { "0056A7", "Endeavour" },
            new[] { "00581A", "Camarone" },
            new[] { "0066CC", "Science Blue" },
            new[] { "0066FF", "Blue Ribbon" },
            new[] { "00755E", "Tropical Rain Forest" },
            new[] { "0076A3", "Allports" },
            new[] { "007BA7", "Deep Cerulean" },
            new[] { "007EC7", "Lochmara" },
            new[] { "007FFF", "Azure Radiance" },
            new[] { "008080", "Teal" },
            new[] { "0095B6", "Bondi Blue" },
            new[] { "009DC4", "Pacific Blue" },
            new[] { "00A693", "Persian Green" },
            new[] { "00A86B", "Jade" },
            new[] { "00CC99", "Caribbean Green" },
            new[] { "00CCCC", "Robin's Egg Blue" },
            new[] { "00FF00", "Green" },
            new[] { "00FF7F", "Spring Green" },
            new[] { "00FFFF", "Cyan / Aqua" },
            new[] { "010D1A", "Blue Charcoal" },
            new[] { "011635", "Midnight" },
            new[] { "011D13", "Holly" },
            new[] { "012731", "Daintree" },
            new[] { "01361C", "Cardin Green" },
            new[] { "01371A", "County Green" },
            new[] { "013E62", "Astronaut Blue" },
            new[] { "013F6A", "Regal Blue" },
            new[] { "014B43", "Aqua Deep" },
            new[] { "015E85", "Orient" },
            new[] { "016162", "Blue Stone" },
            new[] { "016D39", "Fun Green" },
            new[] { "01796F", "Pine Green" },
            new[] { "017987", "Blue Lagoon" },
            new[] { "01826B", "Deep Sea" },
            new[] { "01A368", "Green Haze" },
            new[] { "022D15", "English Holly" },
            new[] { "02402C", "Sherwood Green" },
            new[] { "02478E", "Congress Blue" },
            new[] { "024E46", "Evening Sea" },
            new[] { "026395", "Bahama Blue" },
            new[] { "02866F", "Observatory" },
            new[] { "02A4D3", "Cerulean" },
            new[] { "03163C", "Tangaroa" },
            new[] { "032B52", "Green Vogue" },
            new[] { "036A6E", "Mosque" },
            new[] { "041004", "Midnight Moss" },
            new[] { "041322", "Black Pearl" },
            new[] { "042E4C", "Blue Whale" },
            new[] { "044022", "Zuccini" },
            new[] { "044259", "Teal Blue" },
            new[] { "051040", "Deep Cove" },
            new[] { "051657", "Gulf Blue" },
            new[] { "055989", "Venice Blue" },
            new[] { "056F57", "Watercourse" },
            new[] { "062A78", "Catalina Blue" },
            new[] { "063537", "Tiber" },
            new[] { "069B81", "Gossamer" },
            new[] { "06A189", "Niagara" },
            new[] { "073A50", "Tarawera" },
            new[] { "080110", "Jaguar" },
            new[] { "081910", "Black Bean" },
            new[] { "082567", "Deep Sapphire" },
            new[] { "088370", "Elf Green" },
            new[] { "08E8DE", "Bright Turquoise" },
            new[] { "092256", "Downriver" },
            new[] { "09230F", "Palm Green" },
            new[] { "09255D", "Madison" },
            new[] { "093624", "Bottle Green" },
            new[] { "095859", "Deep Sea Green" },
            new[] { "097F4B", "Salem" },
            new[] { "0A001C", "Black Russian" },
            new[] { "0A480D", "Dark Fern" },
            new[] { "0A6906", "Japanese Laurel" },
            new[] { "0A6F75", "Atoll" },
            new[] { "0B0B0B", "Cod Gray" },
            new[] { "0B0F08", "Marshland" },
            new[] { "0B1107", "Gordons Green" },
            new[] { "0B1304", "Black Forest" },
            new[] { "0B6207", "San Felix" },
            new[] { "0BDA51", "Malachite" },
            new[] { "0C0B1D", "Ebony" },
            new[] { "0C0D0F", "Woodsmoke" },
            new[] { "0C1911", "Racing Green" },
            new[] { "0C7A79", "Surfie Green" },
            new[] { "0C8990", "Blue Chill" },
            new[] { "0D0332", "Black Rock" },
            new[] { "0D1117", "Bunker" },
            new[] { "0D1C19", "Aztec" },
            new[] { "0D2E1C", "Bush" },
            new[] { "0E0E18", "Cinder" },
            new[] { "0E2A30", "Firefly" },
            new[] { "0F2D9E", "Torea Bay" },
            new[] { "10121D", "Vulcan" },
            new[] { "101405", "Green Waterloo" },
            new[] { "105852", "Eden" },
            new[] { "110C6C", "Arapawa" },
            new[] { "120A8F", "Ultramarine" },
            new[] { "123447", "Elephant" },
            new[] { "126B40", "Jewel" },
            new[] { "130000", "Diesel" },
            new[] { "130A06", "Asphalt" },
            new[] { "13264D", "Blue Zodiac" },
            new[] { "134F19", "Parsley" },
            new[] { "140600", "Nero" },
            new[] { "1450AA", "Tory Blue" },
            new[] { "151F4C", "Bunting" },
            new[] { "1560BD", "Denim" },
            new[] { "15736B", "Genoa" },
            new[] { "161928", "Mirage" },
            new[] { "161D10", "Hunter Green" },
            new[] { "162A40", "Big Stone" },
            new[] { "163222", "Celtic" },
            new[] { "16322C", "Timber Green" },
            new[] { "163531", "Gable Green" },
            new[] { "171F04", "Pine Tree" },
            new[] { "175579", "Chathams Blue" },
            new[] { "182D09", "Deep Forest Green" },
            new[] { "18587A", "Blumine" },
            new[] { "19330E", "Palm Leaf" },
            new[] { "193751", "Nile Blue" },
            new[] { "1959A8", "Fun Blue" },
            new[] { "1A1A68", "Lucky Point" },
            new[] { "1AB385", "Mountain Meadow" },
            new[] { "1B0245", "Tolopea" },
            new[] { "1B1035", "Haiti" },
            new[] { "1B127B", "Deep Koamaru" },
            new[] { "1B1404", "Acadia" },
            new[] { "1B2F11", "Seaweed" },
            new[] { "1B3162", "Biscay" },
            new[] { "1B659D", "Matisse" },
            new[] { "1C1208", "Crowshead" },
            new[] { "1C1E13", "Rangoon Green" },
            new[] { "1C39BB", "Persian Blue" },
            new[] { "1C402E", "Everglade" },
            new[] { "1C7C7D", "Elm" },
            new[] { "1D6142", "Green Pea" },
            new[] { "1E0F04", "Creole" },
            new[] { "1E1609", "Karaka" },
            new[] { "1E1708", "El Paso" },
            new[] { "1E385B", "Cello" },
            new[] { "1E433C", "Te Papa Green" },
            new[] { "1E90FF", "Dodger Blue" },
            new[] { "1E9AB0", "Eastern Blue" },
            new[] { "1F120F", "Night Rider" },
            new[] { "1FC2C2", "Java" },
            new[] { "20208D", "Jacksons Purple" },
            new[] { "202E54", "Cloud Burst" },
            new[] { "204852", "Blue Dianne" },
            new[] { "211A0E", "Eternity" },
            new[] { "220878", "Deep Blue" },
            new[] { "228B22", "Forest Green" },
            new[] { "233418", "Mallard" },
            new[] { "240A40", "Violet" },
            new[] { "240C02", "Kilamanjaro" },
            new[] { "242A1D", "Log Cabin" },
            new[] { "242E16", "Black Olive" },
            new[] { "24500F", "Green House" },
            new[] { "251607", "Graphite" },
            new[] { "251706", "Cannon Black" },
            new[] { "251F4F", "Port Gore" },
            new[] { "25272C", "Shark" },
            new[] { "25311C", "Green Kelp" },
            new[] { "2596D1", "Curious Blue" },
            new[] { "260368", "Paua" },
            new[] { "26056A", "Paris M" },
            new[] { "261105", "Wood Bark" },
            new[] { "261414", "Gondola" },
            new[] { "262335", "Steel Gray" },
            new[] { "26283B", "Ebony Clay" },
            new[] { "273A81", "Bay of Many" },
            new[] { "27504B", "Plantation" },
            new[] { "278A5B", "Eucalyptus" },
            new[] { "281E15", "Oil" },
            new[] { "283A77", "Astronaut" },
            new[] { "286ACD", "Mariner" },
            new[] { "290C5E", "Violent Violet" },
            new[] { "292130", "Bastille" },
            new[] { "292319", "Zeus" },
            new[] { "292937", "Charade" },
            new[] { "297B9A", "Jelly Bean" },
            new[] { "29AB87", "Jungle Green" },
            new[] { "2A0359", "Cherry Pie" },
            new[] { "2A140E", "Coffee Bean" },
            new[] { "2A2630", "Baltic Sea" },
            new[] { "2A380B", "Turtle Green" },
            new[] { "2A52BE", "Cerulean Blue" },
            new[] { "2B0202", "Sepia Black" },
            new[] { "2B194F", "Valhalla" },
            new[] { "2B3228", "Heavy Metal" },
            new[] { "2C0E8C", "Blue Gem" },
            new[] { "2C1632", "Revolver" },
            new[] { "2C2133", "Bleached Cedar" },
            new[] { "2C8C84", "Lochinvar" },
            new[] { "2D2510", "Mikado" },
            new[] { "2D383A", "Outer Space" },
            new[] { "2D569B", "St Tropaz" },
            new[] { "2E0329", "Jacaranda" },
            new[] { "2E1905", "Jacko Bean" },
            new[] { "2E3222", "Rangitoto" },
            new[] { "2E3F62", "Rhino" },
            new[] { "2E8B57", "Sea Green" },
            new[] { "2EBFD4", "Scooter" },
            new[] { "2F270E", "Onion" },
            new[] { "2F3CB3", "Governor Bay" },
            new[] { "2F519E", "Sapphire" },
            new[] { "2F5A57", "Spectra" },
            new[] { "2F6168", "Casal" },
            new[] { "300529", "Melanzane" },
            new[] { "301F1E", "Cocoa Brown" },
            new[] { "302A0F", "Woodrush" },
            new[] { "304B6A", "San Juan" },
            new[] { "30D5C8", "Turquoise" },
            new[] { "311C17", "Eclipse" },
            new[] { "314459", "Pickled Bluewood" },
            new[] { "315BA1", "Azure" },
            new[] { "31728D", "Calypso" },
            new[] { "317D82", "Paradiso" },
            new[] { "32127A", "Persian Indigo" },
            new[] { "32293A", "Blackcurrant" },
            new[] { "323232", "Mine Shaft" },
            new[] { "325D52", "Stromboli" },
            new[] { "327C14", "Bilbao" },
            new[] { "327DA0", "Astral" },
            new[] { "33036B", "Christalle" },
            new[] { "33292F", "Thunder" },
            new[] { "33CC99", "Shamrock" },
            new[] { "341515", "Tamarind" },
            new[] { "350036", "Mardi Gras" },
            new[] { "350E42", "Valentino" },
            new[] { "350E57", "Jagger" },
            new[] { "353542", "Tuna" },
            new[] { "354E8C", "Chambray" },
            new[] { "363050", "Martinique" },
            new[] { "363534", "Tuatara" },
            new[] { "363C0D", "Waiouru" },
            new[] { "36747D", "Ming" },
            new[] { "368716", "La Palma" },
            new[] { "370202", "Chocolate" },
            new[] { "371D09", "Clinker" },
            new[] { "37290E", "Brown Tumbleweed" },
            new[] { "373021", "Birch" },
            new[] { "377475", "Oracle" },
            new[] { "380474", "Blue Diamond" },
            new[] { "381A51", "Grape" },
            new[] { "383533", "Dune" },
            new[] { "384555", "Oxford Blue" },
            new[] { "384910", "Clover" },
            new[] { "394851", "Limed Spruce" },
            new[] { "396413", "Dell" },
            new[] { "3A0020", "Toledo" },
            new[] { "3A2010", "Sambuca" },
            new[] { "3A2A6A", "Jacarta" },
            new[] { "3A686C", "William" },
            new[] { "3A6A47", "Killarney" },
            new[] { "3AB09E", "Keppel" },
            new[] { "3B000B", "Temptress" },
            new[] { "3B0910", "Aubergine" },
            new[] { "3B1F1F", "Jon" },
            new[] { "3B2820", "Treehouse" },
            new[] { "3B7A57", "Amazon" },
            new[] { "3B91B4", "Boston Blue" },
            new[] { "3C0878", "Windsor" },
            new[] { "3C1206", "Rebel" },
            new[] { "3C1F76", "Meteorite" },
            new[] { "3C2005", "Dark Ebony" },
            new[] { "3C3910", "Camouflage" },
            new[] { "3C4151", "Bright Gray" },
            new[] { "3C4443", "Cape Cod" },
            new[] { "3C493A", "Lunar Green" },
            new[] { "3D0C02", "Bean  " },
            new[] { "3D2B1F", "Bistre" },
            new[] { "3D7D52", "Goblin" },
            new[] { "3E0480", "Kingfisher Daisy" },
            new[] { "3E1C14", "Cedar" },
            new[] { "3E2B23", "English Walnut" },
            new[] { "3E2C1C", "Black Marlin" },
            new[] { "3E3A44", "Ship Gray" },
            new[] { "3EABBF", "Pelorous" },
            new[] { "3F2109", "Bronze" },
            new[] { "3F2500", "Cola" },
            new[] { "3F3002", "Madras" },
            new[] { "3F307F", "Minsk" },
            new[] { "3F4C3A", "Cabbage Pont" },
            new[] { "3F583B", "Tom Thumb" },
            new[] { "3F5D53", "Mineral Green" },
            new[] { "3FC1AA", "Puerto Rico" },
            new[] { "3FFF00", "Harlequin" },
            new[] { "401801", "Brown Pod" },
            new[] { "40291D", "Cork" },
            new[] { "403B38", "Masala" },
            new[] { "403D19", "Thatch Green" },
            new[] { "405169", "Fiord" },
            new[] { "40826D", "Viridian" },
            new[] { "40A860", "Chateau Green" },
            new[] { "410056", "Ripe Plum" },
            new[] { "411F10", "Paco" },
            new[] { "412010", "Deep Oak" },
            new[] { "413C37", "Merlin" },
            new[] { "414257", "Gun Powder" },
            new[] { "414C7D", "East Bay" },
            new[] { "4169E1", "Royal Blue" },
            new[] { "41AA78", "Ocean Green" },
            new[] { "420303", "Burnt Maroon" },
            new[] { "423921", "Lisbon Brown" },
            new[] { "427977", "Faded Jade" },
            new[] { "431560", "Scarlet Gum" },
            new[] { "433120", "Iroko" },
            new[] { "433E37", "Armadillo" },
            new[] { "434C59", "River Bed" },
            new[] { "436A0D", "Green Leaf" },
            new[] { "44012D", "Barossa" },
            new[] { "441D00", "Morocco Brown" },
            new[] { "444954", "Mako" },
            new[] { "454936", "Kelp" },
            new[] { "456CAC", "San Marino" },
            new[] { "45B1E8", "Picton Blue" },
            new[] { "460B41", "Loulou" },
            new[] { "462425", "Crater Brown" },
            new[] { "465945", "Gray Asparagus" },
            new[] { "4682B4", "Steel Blue" },
            new[] { "480404", "Rustic Red" },
            new[] { "480607", "Bulgarian Rose" },
            new[] { "480656", "Clairvoyant" },
            new[] { "481C1C", "Cocoa Bean" },
            new[] { "483131", "Woody Brown" },
            new[] { "483C32", "Taupe" },
            new[] { "49170C", "Van Cleef" },
            new[] { "492615", "Brown Derby" },
            new[] { "49371B", "Metallic Bronze" },
            new[] { "495400", "Verdun Green" },
            new[] { "496679", "Blue Bayoux" },
            new[] { "497183", "Bismark" },
            new[] { "4A2A04", "Bracken" },
            new[] { "4A3004", "Deep Bronze" },
            new[] { "4A3C30", "Mondo" },
            new[] { "4A4244", "Tundora" },
            new[] { "4A444B", "Gravel" },
            new[] { "4A4E5A", "Trout" },
            new[] { "4B0082", "Pigment Indigo" },
            new[] { "4B5D52", "Nandor" },
            new[] { "4C3024", "Saddle" },
            new[] { "4C4F56", "Abbey" },
            new[] { "4D0135", "Blackberry" },
            new[] { "4D0A18", "Cab Sav" },
            new[] { "4D1E01", "Indian Tan" },
            new[] { "4D282D", "Cowboy" },
            new[] { "4D282E", "Livid Brown" },
            new[] { "4D3833", "Rock" },
            new[] { "4D3D14", "Punga" },
            new[] { "4D400F", "Bronzetone" },
            new[] { "4D5328", "Woodland" },
            new[] { "4E0606", "Mahogany" },
            new[] { "4E2A5A", "Bossanova" },
            new[] { "4E3B41", "Matterhorn" },
            new[] { "4E420C", "Bronze Olive" },
            new[] { "4E4562", "Mulled Wine" },
            new[] { "4E6649", "Axolotl" },
            new[] { "4E7F9E", "Wedgewood" },
            new[] { "4EABD1", "Shakespeare" },
            new[] { "4F1C70", "Honey Flower" },
            new[] { "4F2398", "Daisy Bush" },
            new[] { "4F69C6", "Indigo" },
            new[] { "4F7942", "Fern Green" },
            new[] { "4F9D5D", "Fruit Salad" },
            new[] { "4FA83D", "Apple" },
            new[] { "504351", "Mortar" },
            new[] { "507096", "Kashmir Blue" },
            new[] { "507672", "Cutty Sark" },
            new[] { "50C878", "Emerald" },
            new[] { "514649", "Emperor" },
            new[] { "516E3D", "Chalet Green" },
            new[] { "517C66", "Como" },
            new[] { "51808F", "Smalt Blue" },
            new[] { "52001F", "Castro" },
            new[] { "520C17", "Maroon Oak" },
            new[] { "523C94", "Gigas" },
            new[] { "533455", "Voodoo" },
            new[] { "534491", "Victoria" },
            new[] { "53824B", "Hippie Green" },
            new[] { "541012", "Heath" },
            new[] { "544333", "Judge Gray" },
            new[] { "54534D", "Fuscous Gray" },
            new[] { "549019", "Vida Loca" },
            new[] { "55280C", "Cioccolato" },
            new[] { "555B10", "Saratoga" },
            new[] { "556D56", "Finlandia" },
            new[] { "5590D9", "Havelock Blue" },
            new[] { "56B4BE", "Fountain Blue" },
            new[] { "578363", "Spring Leaves" },
            new[] { "583401", "Saddle Brown" },
            new[] { "585562", "Scarpa Flow" },
            new[] { "587156", "Cactus" },
            new[] { "589AAF", "Hippie Blue" },
            new[] { "591D35", "Wine Berry" },
            new[] { "592804", "Brown Bramble" },
            new[] { "593737", "Congo Brown" },
            new[] { "594433", "Millbrook" },
            new[] { "5A6E9C", "Waikawa Gray" },
            new[] { "5A87A0", "Horizon" },
            new[] { "5B3013", "Jambalaya" },
            new[] { "5C0120", "Bordeaux" },
            new[] { "5C0536", "Mulberry Wood" },
            new[] { "5C2E01", "Carnaby Tan" },
            new[] { "5C5D75", "Comet" },
            new[] { "5D1E0F", "Redwood" },
            new[] { "5D4C51", "Don Juan" },
            new[] { "5D5C58", "Chicago" },
            new[] { "5D5E37", "Verdigris" },
            new[] { "5D7747", "Dingley" },
            new[] { "5DA19F", "Breaker Bay" },
            new[] { "5E483E", "Kabul" },
            new[] { "5E5D3B", "Hemlock" },
            new[] { "5F3D26", "Irish Coffee" },
            new[] { "5F5F6E", "Mid Gray" },
            new[] { "5F6672", "Shuttle Gray" },
            new[] { "5FA777", "Aqua Forest" },
            new[] { "5FB3AC", "Tradewind" },
            new[] { "604913", "Horses Neck" },
            new[] { "605B73", "Smoky" },
            new[] { "606E68", "Corduroy" },
            new[] { "6093D1", "Danube" },
            new[] { "612718", "Espresso" },
            new[] { "614051", "Eggplant" },
            new[] { "615D30", "Costa Del Sol" },
            new[] { "61845F", "Glade Green" },
            new[] { "622F30", "Buccaneer" },
            new[] { "623F2D", "Quincy" },
            new[] { "624E9A", "Butterfly Bush" },
            new[] { "625119", "West Coast" },
            new[] { "626649", "Finch" },
            new[] { "639A8F", "Patina" },
            new[] { "63B76C", "Fern" },
            new[] { "6456B7", "Blue Violet" },
            new[] { "646077", "Dolphin" },
            new[] { "646463", "Storm Dust" },
            new[] { "646A54", "Siam" },
            new[] { "646E75", "Nevada" },
            new[] { "6495ED", "Cornflower Blue" },
            new[] { "64CCDB", "Viking" },
            new[] { "65000B", "Rosewood" },
            new[] { "651A14", "Cherrywood" },
            new[] { "652DC1", "Purple Heart" },
            new[] { "657220", "Fern Frond" },
            new[] { "65745D", "Willow Grove" },
            new[] { "65869F", "Hoki" },
            new[] { "660045", "Pompadour" },
            new[] { "660099", "Purple" },
            new[] { "66023C", "Tyrian Purple" },
            new[] { "661010", "Dark Tan" },
            new[] { "66B58F", "Silver Tree" },
            new[] { "66FF00", "Bright Green" },
            new[] { "66FF66", "Screamin' Green" },
            new[] { "67032D", "Black Rose" },
            new[] { "675FA6", "Scampi" },
            new[] { "676662", "Ironside Gray" },
            new[] { "678975", "Viridian Green" },
            new[] { "67A712", "Christi" },
            new[] { "683600", "Nutmeg Wood Finish" },
            new[] { "685558", "Zambezi" },
            new[] { "685E6E", "Salt Box" },
            new[] { "692545", "Tawny Port" },
            new[] { "692D54", "Finn" },
            new[] { "695F62", "Scorpion" },
            new[] { "697E9A", "Lynch" },
            new[] { "6A442E", "Spice" },
            new[] { "6A5D1B", "Himalaya" },
            new[] { "6A6051", "Soya Bean" },
            new[] { "6B2A14", "Hairy Heath" },
            new[] { "6B3FA0", "Royal Purple" },
            new[] { "6B4E31", "Shingle Fawn" },
            new[] { "6B5755", "Dorado" },
            new[] { "6B8BA2", "Bermuda Gray" },
            new[] { "6B8E23", "Olive Drab" },
            new[] { "6C3082", "Eminence" },
            new[] { "6CDAE7", "Turquoise Blue" },
            new[] { "6D0101", "Lonestar" },
            new[] { "6D5E54", "Pine Cone" },
            new[] { "6D6C6C", "Dove Gray" },
            new[] { "6D9292", "Juniper" },
            new[] { "6D92A1", "Gothic" },
            new[] { "6E0902", "Red Oxide" },
            new[] { "6E1D14", "Moccaccino" },
            new[] { "6E4826", "Pickled Bean" },
            new[] { "6E4B26", "Dallas" },
            new[] { "6E6D57", "Kokoda" },
            new[] { "6E7783", "Pale Sky" },
            new[] { "6F440C", "Cafe Royale" },
            new[] { "6F6A61", "Flint" },
            new[] { "6F8E63", "Highland" },
            new[] { "6F9D02", "Limeade" },
            new[] { "6FD0C5", "Downy" },
            new[] { "701C1C", "Persian Plum" },
            new[] { "704214", "Sepia" },
            new[] { "704A07", "Antique Bronze" },
            new[] { "704F50", "Ferra" },
            new[] { "706555", "Coffee" },
            new[] { "708090", "Slate Gray" },
            new[] { "711A00", "Cedar Wood Finish" },
            new[] { "71291D", "Metallic Copper" },
            new[] { "714693", "Affair" },
            new[] { "714AB2", "Studio" },
            new[] { "715D47", "Tobacco Brown" },
            new[] { "716338", "Yellow Metal" },
            new[] { "716B56", "Peat" },
            new[] { "716E10", "Olivetone" },
            new[] { "717486", "Storm Gray" },
            new[] { "718080", "Sirocco" },
            new[] { "71D9E2", "Aquamarine Blue" },
            new[] { "72010F", "Venetian Red" },
            new[] { "724A2F", "Old Copper" },
            new[] { "726D4E", "Go Ben" },
            new[] { "727B89", "Raven" },
            new[] { "731E8F", "Seance" },
            new[] { "734A12", "Raw Umber" },
            new[] { "736C9F", "Kimberly" },
            new[] { "736D58", "Crocodile" },
            new[] { "737829", "Crete" },
            new[] { "738678", "Xanadu" },
            new[] { "74640D", "Spicy Mustard" },
            new[] { "747D63", "Limed Ash" },
            new[] { "747D83", "Rolling Stone" },
            new[] { "748881", "Blue Smoke" },
            new[] { "749378", "Laurel" },
            new[] { "74C365", "Mantis" },
            new[] { "755A57", "Russett" },
            new[] { "7563A8", "Deluge" },
            new[] { "76395D", "Cosmic" },
            new[] { "7666C6", "Blue Marguerite" },
            new[] { "76BD17", "Lima" },
            new[] { "76D7EA", "Sky Blue" },
            new[] { "770F05", "Dark Burgundy" },
            new[] { "771F1F", "Crown of Thorns" },
            new[] { "773F1A", "Walnut" },
            new[] { "776F61", "Pablo" },
            new[] { "778120", "Pacifika" },
            new[] { "779E86", "Oxley" },
            new[] { "77DD77", "Pastel Green" },
            new[] { "780109", "Japanese Maple" },
            new[] { "782D19", "Mocha" },
            new[] { "782F16", "Peanut" },
            new[] { "78866B", "Camouflage Green" },
            new[] { "788A25", "Wasabi" },
            new[] { "788BBA", "Ship Cove" },
            new[] { "78A39C", "Sea Nymph" },
            new[] { "795D4C", "Roman Coffee" },
            new[] { "796878", "Old Lavender" },
            new[] { "796989", "Rum" },
            new[] { "796A78", "Fedora" },
            new[] { "796D62", "Sandstone" },
            new[] { "79DEEC", "Spray" },
            new[] { "7A013A", "Siren" },
            new[] { "7A58C1", "Fuchsia Blue" },
            new[] { "7A7A7A", "Boulder" },
            new[] { "7A89B8", "Wild Blue Yonder" },
            new[] { "7AC488", "De York" },
            new[] { "7B3801", "Red Beech" },
            new[] { "7B3F00", "Cinnamon" },
            new[] { "7B6608", "Yukon Gold" },
            new[] { "7B7874", "Tapa" },
            new[] { "7B7C94", "Waterloo " },
            new[] { "7B8265", "Flax Smoke" },
            new[] { "7B9F80", "Amulet" },
            new[] { "7BA05B", "Asparagus" },
            new[] { "7C1C05", "Kenyan Copper" },
            new[] { "7C7631", "Pesto" },
            new[] { "7C778A", "Topaz" },
            new[] { "7C7B7A", "Concord" },
            new[] { "7C7B82", "Jumbo" },
            new[] { "7C881A", "Trendy Green" },
            new[] { "7CA1A6", "Gumbo" },
            new[] { "7CB0A1", "Acapulco" },
            new[] { "7CB7BB", "Neptune" },
            new[] { "7D2C14", "Pueblo" },
            new[] { "7DA98D", "Bay Leaf" },
            new[] { "7DC8F7", "Malibu" },
            new[] { "7DD8C6", "Bermuda" },
            new[] { "7E3A15", "Copper Canyon" },
            new[] { "7F1734", "Claret" },
            new[] { "7F3A02", "Peru Tan" },
            new[] { "7F626D", "Falcon" },
            new[] { "7F7589", "Mobster" },
            new[] { "7F76D3", "Moody Blue" },
            new[] { "7FFF00", "Chartreuse" },
            new[] { "7FFFD4", "Aquamarine" },
            new[] { "800000", "Maroon" },
            new[] { "800B47", "Rose Bud Cherry" },
            new[] { "801818", "Falu Red" },
            new[] { "80341F", "Red Robin" },
            new[] { "803790", "Vivid Violet" },
            new[] { "80461B", "Russet" },
            new[] { "807E79", "Friar Gray" },
            new[] { "808000", "Olive" },
            new[] { "808080", "Gray" },
            new[] { "80B3AE", "Gulf Stream" },
            new[] { "80B3C4", "Glacier" },
            new[] { "80CCEA", "Seagull" },
            new[] { "81422C", "Nutmeg" },
            new[] { "816E71", "Spicy Pink" },
            new[] { "817377", "Empress" },
            new[] { "819885", "Spanish Green" },
            new[] { "826F65", "Sand Dune" },
            new[] { "828685", "Gunsmoke" },
            new[] { "828F72", "Battleship Gray" },
            new[] { "831923", "Merlot" },
            new[] { "837050", "Shadow" },
            new[] { "83AA5D", "Chelsea Cucumber" },
            new[] { "83D0C6", "Monte Carlo" },
            new[] { "843179", "Plum" },
            new[] { "84A0A0", "Granny Smith" },
            new[] { "8581D9", "Chetwode Blue" },
            new[] { "858470", "Bandicoot" },
            new[] { "859FAF", "Bali Hai" },
            new[] { "85C4CC", "Half Baked" },
            new[] { "860111", "Red Devil" },
            new[] { "863C3C", "Lotus" },
            new[] { "86483C", "Ironstone" },
            new[] { "864D1E", "Bull Shot" },
            new[] { "86560A", "Rusty Nail" },
            new[] { "868974", "Bitter" },
            new[] { "86949F", "Regent Gray" },
            new[] { "871550", "Disco" },
            new[] { "87756E", "Americano" },
            new[] { "877C7B", "Hurricane" },
            new[] { "878D91", "Oslo Gray" },
            new[] { "87AB39", "Sushi" },
            new[] { "885342", "Spicy Mix" },
            new[] { "886221", "Kumera" },
            new[] { "888387", "Suva Gray" },
            new[] { "888D65", "Avocado" },
            new[] { "893456", "Camelot" },
            new[] { "893843", "Solid Pink" },
            new[] { "894367", "Cannon Pink" },
            new[] { "897D6D", "Makara" },
            new[] { "8A3324", "Burnt Umber" },
            new[] { "8A73D6", "True V" },
            new[] { "8A8360", "Clay Creek" },
            new[] { "8A8389", "Monsoon" },
            new[] { "8A8F8A", "Stack" },
            new[] { "8AB9F1", "Jordy Blue" },
            new[] { "8B00FF", "Electric Violet" },
            new[] { "8B0723", "Monarch" },
            new[] { "8B6B0B", "Corn Harvest" },
            new[] { "8B8470", "Olive Haze" },
            new[] { "8B847E", "Schooner" },
            new[] { "8B8680", "Natural Gray" },
            new[] { "8B9C90", "Mantle" },
            new[] { "8B9FEE", "Portage" },
            new[] { "8BA690", "Envy" },
            new[] { "8BA9A5", "Cascade" },
            new[] { "8BE6D8", "Riptide" },
            new[] { "8C055E", "Cardinal Pink" },
            new[] { "8C472F", "Mule Fawn" },
            new[] { "8C5738", "Potters Clay" },
            new[] { "8C6495", "Trendy Pink" },
            new[] { "8D0226", "Paprika" },
            new[] { "8D3D38", "Sanguine Brown" },
            new[] { "8D3F3F", "Tosca" },
            new[] { "8D7662", "Cement" },
            new[] { "8D8974", "Granite Green" },
            new[] { "8D90A1", "Manatee" },
            new[] { "8DA8CC", "Polo Blue" },
            new[] { "8E0000", "Red Berry" },
            new[] { "8E4D1E", "Rope" },
            new[] { "8E6F70", "Opium" },
            new[] { "8E775E", "Domino" },
            new[] { "8E8190", "Mamba" },
            new[] { "8EABC1", "Nepal" },
            new[] { "8F021C", "Pohutukawa" },
            new[] { "8F3E33", "El Salva" },
            new[] { "8F4B0E", "Korma" },
            new[] { "8F8176", "Squirrel" },
            new[] { "8FD6B4", "Vista Blue" },
            new[] { "900020", "Burgundy" },
            new[] { "901E1E", "Old Brick" },
            new[] { "907874", "Hemp" },
            new[] { "907B71", "Almond Frost" },
            new[] { "908D39", "Sycamore" },
            new[] { "92000A", "Sangria" },
            new[] { "924321", "Cumin" },
            new[] { "926F5B", "Beaver" },
            new[] { "928573", "Stonewall" },
            new[] { "928590", "Venus" },
            new[] { "9370DB", "Medium Purple" },
            new[] { "93CCEA", "Cornflower" },
            new[] { "93DFB8", "Algae Green" },
            new[] { "944747", "Copper Rust" },
            new[] { "948771", "Arrowtown" },
            new[] { "950015", "Scarlett" },
            new[] { "956387", "Strikemaster" },
            new[] { "959396", "Mountain Mist" },
            new[] { "960018", "Carmine" },
            new[] { "964B00", "Brown" },
            new[] { "967059", "Leather" },
            new[] { "9678B6", "Purple Mountain's Majesty" },
            new[] { "967BB6", "Lavender Purple" },
            new[] { "96A8A1", "Pewter" },
            new[] { "96BBAB", "Summer Green" },
            new[] { "97605D", "Au Chico" },
            new[] { "9771B5", "Wisteria" },
            new[] { "97CD2D", "Atlantis" },
            new[] { "983D61", "Vin Rouge" },
            new[] { "9874D3", "Lilac Bush" },
            new[] { "98777B", "Bazaar" },
            new[] { "98811B", "Hacienda" },
            new[] { "988D77", "Pale Oyster" },
            new[] { "98FF98", "Mint Green" },
            new[] { "990066", "Fresh Eggplant" },
            new[] { "991199", "Violet Eggplant" },
            new[] { "991613", "Tamarillo" },
            new[] { "991B07", "Totem Pole" },
            new[] { "996666", "Copper Rose" },
            new[] { "9966CC", "Amethyst" },
            new[] { "997A8D", "Mountbatten Pink" },
            new[] { "9999CC", "Blue Bell" },
            new[] { "9A3820", "Prairie Sand" },
            new[] { "9A6E61", "Toast" },
            new[] { "9A9577", "Gurkha" },
            new[] { "9AB973", "Olivine" },
            new[] { "9AC2B8", "Shadow Green" },
            new[] { "9B4703", "Oregon" },
            new[] { "9B9E8F", "Lemon Grass" },
            new[] { "9C3336", "Stiletto" },
            new[] { "9D5616", "Hawaiian Tan" },
            new[] { "9DACB7", "Gull Gray" },
            new[] { "9DC209", "Pistachio" },
            new[] { "9DE093", "Granny Smith Apple" },
            new[] { "9DE5FF", "Anakiwa" },
            new[] { "9E5302", "Chelsea Gem" },
            new[] { "9E5B40", "Sepia Skin" },
            new[] { "9EA587", "Sage" },
            new[] { "9EA91F", "Citron" },
            new[] { "9EB1CD", "Rock Blue" },
            new[] { "9EDEE0", "Morning Glory" },
            new[] { "9F381D", "Cognac" },
            new[] { "9F821C", "Reef Gold" },
            new[] { "9F9F9C", "Star Dust" },
            new[] { "9FA0B1", "Santas Gray" },
            new[] { "9FD7D3", "Sinbad" },
            new[] { "9FDD8C", "Feijoa" },
            new[] { "A02712", "Tabasco" },
            new[] { "A1750D", "Buttered Rum" },
            new[] { "A1ADB5", "Hit Gray" },
            new[] { "A1C50A", "Citrus" },
            new[] { "A1DAD7", "Aqua Island" },
            new[] { "A1E9DE", "Water Leaf" },
            new[] { "A2006D", "Flirt" },
            new[] { "A23B6C", "Rouge" },
            new[] { "A26645", "Cape Palliser" },
            new[] { "A2AAB3", "Gray Chateau" },
            new[] { "A2AEAB", "Edward" },
            new[] { "A3807B", "Pharlap" },
            new[] { "A397B4", "Amethyst Smoke" },
            new[] { "A3E3ED", "Blizzard Blue" },
            new[] { "A4A49D", "Delta" },
            new[] { "A4A6D3", "Wistful" },
            new[] { "A4AF6E", "Green Smoke" },
            new[] { "A50B5E", "Jazzberry Jam" },
            new[] { "A59B91", "Zorba" },
            new[] { "A5CB0C", "Bahia" },
            new[] { "A62F20", "Roof Terracotta" },
            new[] { "A65529", "Paarl" },
            new[] { "A68B5B", "Barley Corn" },
            new[] { "A69279", "Donkey Brown" },
            new[] { "A6A29A", "Dawn" },
            new[] { "A72525", "Mexican Red" },
            new[] { "A7882C", "Luxor Gold" },
            new[] { "A85307", "Rich Gold" },
            new[] { "A86515", "Reno Sand" },
            new[] { "A86B6B", "Coral Tree" },
            new[] { "A8989B", "Dusty Gray" },
            new[] { "A899E6", "Dull Lavender" },
            new[] { "A8A589", "Tallow" },
            new[] { "A8AE9C", "Bud" },
            new[] { "A8AF8E", "Locust" },
            new[] { "A8BD9F", "Norway" },
            new[] { "A8E3BD", "Chinook" },
            new[] { "A9A491", "Gray Olive" },
            new[] { "A9ACB6", "Aluminium" },
            new[] { "A9B2C3", "Cadet Blue" },
            new[] { "A9B497", "Schist" },
            new[] { "A9BDBF", "Tower Gray" },
            new[] { "A9BEF2", "Perano" },
            new[] { "A9C6C2", "Opal" },
            new[] { "AA375A", "Night Shadz" },
            new[] { "AA4203", "Fire" },
            new[] { "AA8B5B", "Muesli" },
            new[] { "AA8D6F", "Sandal" },
            new[] { "AAA5A9", "Shady Lady" },
            new[] { "AAA9CD", "Logan" },
            new[] { "AAABB7", "Spun Pearl" },
            new[] { "AAD6E6", "Regent St Blue" },
            new[] { "AAF0D1", "Magic Mint" },
            new[] { "AB0563", "Lipstick" },
            new[] { "AB3472", "Royal Heath" },
            new[] { "AB917A", "Sandrift" },
            new[] { "ABA0D9", "Cold Purple" },
            new[] { "ABA196", "Bronco" },
            new[] { "AC8A56", "Limed Oak" },
            new[] { "AC91CE", "East Side" },
            new[] { "AC9E22", "Lemon Ginger" },
            new[] { "ACA494", "Napa" },
            new[] { "ACA586", "Hillary" },
            new[] { "ACA59F", "Cloudy" },
            new[] { "ACACAC", "Silver Chalice" },
            new[] { "ACB78E", "Swamp Green" },
            new[] { "ACCBB1", "Spring Rain" },
            new[] { "ACDD4D", "Conifer" },
            new[] { "ACE1AF", "Celadon" },
            new[] { "AD781B", "Mandalay" },
            new[] { "ADBED1", "Casper" },
            new[] { "ADDFAD", "Moss Green" },
            new[] { "ADE6C4", "Padua" },
            new[] { "ADFF2F", "Green Yellow" },
            new[] { "AE4560", "Hippie Pink" },
            new[] { "AE6020", "Desert" },
            new[] { "AE809E", "Bouquet" },
            new[] { "AF4035", "Medium Carmine" },
            new[] { "AF4D43", "Apple Blossom" },
            new[] { "AF593E", "Brown Rust" },
            new[] { "AF8751", "Driftwood" },
            new[] { "AF8F2C", "Alpine" },
            new[] { "AF9F1C", "Lucky" },
            new[] { "AFA09E", "Martini" },
            new[] { "AFB1B8", "Bombay" },
            new[] { "AFBDD9", "Pigeon Post" },
            new[] { "B04C6A", "Cadillac" },
            new[] { "B05D54", "Matrix" },
            new[] { "B05E81", "Tapestry" },
            new[] { "B06608", "Mai Tai" },
            new[] { "B09A95", "Del Rio" },
            new[] { "B0E0E6", "Powder Blue" },
            new[] { "B0E313", "Inch Worm" },
            new[] { "B10000", "Bright Red" },
            new[] { "B14A0B", "Vesuvius" },
            new[] { "B1610B", "Pumpkin Skin" },
            new[] { "B16D52", "Santa Fe" },
            new[] { "B19461", "Teak" },
            new[] { "B1E2C1", "Fringy Flower" },
            new[] { "B1F4E7", "Ice Cold" },
            new[] { "B20931", "Shiraz" },
            new[] { "B2A1EA", "Biloba Flower" },
            new[] { "B32D29", "Tall Poppy" },
            new[] { "B35213", "Fiery Orange" },
            new[] { "B38007", "Hot Toddy" },
            new[] { "B3AF95", "Taupe Gray" },
            new[] { "B3C110", "La Rioja" },
            new[] { "B43332", "Well Read" },
            new[] { "B44668", "Blush" },
            new[] { "B4CFD3", "Jungle Mist" },
            new[] { "B57281", "Turkish Rose" },
            new[] { "B57EDC", "Lavender" },
            new[] { "B5A27F", "Mongoose" },
            new[] { "B5B35C", "Olive Green" },
            new[] { "B5D2CE", "Jet Stream" },
            new[] { "B5ECDF", "Cruise" },
            new[] { "B6316C", "Hibiscus" },
            new[] { "B69D98", "Thatch" },
            new[] { "B6B095", "Heathered Gray" },
            new[] { "B6BAA4", "Eagle" },
            new[] { "B6D1EA", "Spindle" },
            new[] { "B6D3BF", "Gum Leaf" },
            new[] { "B7410E", "Rust" },
            new[] { "B78E5C", "Muddy Waters" },
            new[] { "B7A214", "Sahara" },
            new[] { "B7A458", "Husk" },
            new[] { "B7B1B1", "Nobel" },
            new[] { "B7C3D0", "Heather" },
            new[] { "B7F0BE", "Madang" },
            new[] { "B81104", "Milano Red" },
            new[] { "B87333", "Copper" },
            new[] { "B8B56A", "Gimblet" },
            new[] { "B8C1B1", "Green Spring" },
            new[] { "B8C25D", "Celery" },
            new[] { "B8E0F9", "Sail" },
            new[] { "B94E48", "Chestnut" },
            new[] { "B95140", "Crail" },
            new[] { "B98D28", "Marigold" },
            new[] { "B9C46A", "Wild Willow" },
            new[] { "B9C8AC", "Rainee" },
            new[] { "BA0101", "Guardsman Red" },
            new[] { "BA450C", "Rock Spray" },
            new[] { "BA6F1E", "Bourbon" },
            new[] { "BA7F03", "Pirate Gold" },
            new[] { "BAB1A2", "Nomad" },
            new[] { "BAC7C9", "Submarine" },
            new[] { "BAEEF9", "Charlotte" },
            new[] { "BB3385", "Medium Red Violet" },
            new[] { "BB8983", "Brandy Rose" },
            new[] { "BBD009", "Rio Grande" },
            new[] { "BBD7C1", "Surf" },
            new[] { "BCC9C2", "Powder Ash" },
            new[] { "BD5E2E", "Tuscany" },
            new[] { "BD978E", "Quicksand" },
            new[] { "BDB1A8", "Silk" },
            new[] { "BDB2A1", "Malta" },
            new[] { "BDB3C7", "Chatelle" },
            new[] { "BDBBD7", "Lavender Gray" },
            new[] { "BDBDC6", "French Gray" },
            new[] { "BDC8B3", "Clay Ash" },
            new[] { "BDC9CE", "Loblolly" },
            new[] { "BDEDFD", "French Pass" },
            new[] { "BEA6C3", "London Hue" },
            new[] { "BEB5B7", "Pink Swan" },
            new[] { "BEDE0D", "Fuego" },
            new[] { "BF5500", "Rose of Sharon" },
            new[] { "BFB8B0", "Tide" },
            new[] { "BFBED8", "Blue Haze" },
            new[] { "BFC1C2", "Silver Sand" },
            new[] { "BFC921", "Key Lime Pie" },
            new[] { "BFDBE2", "Ziggurat" },
            new[] { "BFFF00", "Lime" },
            new[] { "C02B18", "Thunderbird" },
            new[] { "C04737", "Mojo" },
            new[] { "C08081", "Old Rose" },
            new[] { "C0C0C0", "Silver" },
            new[] { "C0D3B9", "Pale Leaf" },
            new[] { "C0D8B6", "Pixie Green" },
            new[] { "C1440E", "Tia Maria" },
            new[] { "C154C1", "Fuchsia Pink" },
            new[] { "C1A004", "Buddha Gold" },
            new[] { "C1B7A4", "Bison Hide" },
            new[] { "C1BAB0", "Tea" },
            new[] { "C1BECD", "Gray Suit" },
            new[] { "C1D7B0", "Sprout" },
            new[] { "C1F07C", "Sulu" },
            new[] { "C26B03", "Indochine" },
            new[] { "C2955D", "Twine" },
            new[] { "C2BDB6", "Cotton Seed" },
            new[] { "C2CAC4", "Pumice" },
            new[] { "C2E8E5", "Jagged Ice" },
            new[] { "C32148", "Maroon Flush" },
            new[] { "C3B091", "Indian Khaki" },
            new[] { "C3BFC1", "Pale Slate" },
            new[] { "C3C3BD", "Gray Nickel" },
            new[] { "C3CDE6", "Periwinkle Gray" },
            new[] { "C3D1D1", "Tiara" },
            new[] { "C3DDF9", "Tropical Blue" },
            new[] { "C41E3A", "Cardinal" },
            new[] { "C45655", "Fuzzy Wuzzy Brown" },
            new[] { "C45719", "Orange Roughy" },
            new[] { "C4C4BC", "Mist Gray" },
            new[] { "C4D0B0", "Coriander" },
            new[] { "C4F4EB", "Mint Tulip" },
            new[] { "C54B8C", "Mulberry" },
            new[] { "C59922", "Nugget" },
            new[] { "C5994B", "Tussock" },
            new[] { "C5DBCA", "Sea Mist" },
            new[] { "C5E17A", "Yellow Green" },
            new[] { "C62D42", "Brick Red" },
            new[] { "C6726B", "Contessa" },
            new[] { "C69191", "Oriental Pink" },
            new[] { "C6A84B", "Roti" },
            new[] { "C6C3B5", "Ash" },
            new[] { "C6C8BD", "Kangaroo" },
            new[] { "C6E610", "Las Palmas" },
            new[] { "C7031E", "Monza" },
            new[] { "C71585", "Red Violet" },
            new[] { "C7BCA2", "Coral Reef" },
            new[] { "C7C1FF", "Melrose" },
            new[] { "C7C4BF", "Cloud" },
            new[] { "C7C9D5", "Ghost" },
            new[] { "C7CD90", "Pine Glade" },
            new[] { "C7DDE5", "Botticelli" },
            new[] { "C88A65", "Antique Brass" },
            new[] { "C8A2C8", "Lilac" },
            new[] { "C8A528", "Hokey Pokey" },
            new[] { "C8AABF", "Lily" },
            new[] { "C8B568", "Laser" },
            new[] { "C8E3D7", "Edgewater" },
            new[] { "C96323", "Piper" },
            new[] { "C99415", "Pizza" },
            new[] { "C9A0DC", "Light Wisteria" },
            new[] { "C9B29B", "Rodeo Dust" },
            new[] { "C9B35B", "Sundance" },
            new[] { "C9B93B", "Earls Green" },
            new[] { "C9C0BB", "Silver Rust" },
            new[] { "C9D9D2", "Conch" },
            new[] { "C9FFA2", "Reef" },
            new[] { "C9FFE5", "Aero Blue" },
            new[] { "CA3435", "Flush Mahogany" },
            new[] { "CABB48", "Turmeric" },
            new[] { "CADCD4", "Paris White" },
            new[] { "CAE00D", "Bitter Lemon" },
            new[] { "CAE6DA", "Skeptic" },
            new[] { "CB8FA9", "Viola" },
            new[] { "CBCAB6", "Foggy Gray" },
            new[] { "CBD3B0", "Green Mist" },
            new[] { "CBDBD6", "Nebula" },
            new[] { "CC3333", "Persian Red" },
            new[] { "CC5500", "Burnt Orange" },
            new[] { "CC7722", "Ochre" },
            new[] { "CC8899", "Puce" },
            new[] { "CCCAA8", "Thistle Green" },
            new[] { "CCCCFF", "Periwinkle" },
            new[] { "CCFF00", "Electric Lime" },
            new[] { "CD5700", "Tenn" },
            new[] { "CD5C5C", "Chestnut Rose" },
            new[] { "CD8429", "Brandy Punch" },
            new[] { "CDF4FF", "Onahau" },
            new[] { "CEB98F", "Sorrell Brown" },
            new[] { "CEBABA", "Cold Turkey" },
            new[] { "CEC291", "Yuma" },
            new[] { "CEC7A7", "Chino" },
            new[] { "CFA39D", "Eunry" },
            new[] { "CFB53B", "Old Gold" },
            new[] { "CFDCCF", "Tasman" },
            new[] { "CFE5D2", "Surf Crest" },
            new[] { "CFF9F3", "Humming Bird" },
            new[] { "CFFAF4", "Scandal" },
            new[] { "D05F04", "Red Stage" },
            new[] { "D06DA1", "Hopbush" },
            new[] { "D07D12", "Meteor" },
            new[] { "D0BEF8", "Perfume" },
            new[] { "D0C0E5", "Prelude" },
            new[] { "D0F0C0", "Tea Green" },
            new[] { "D18F1B", "Geebung" },
            new[] { "D1BEA8", "Vanilla" },
            new[] { "D1C6B4", "Soft Amber" },
            new[] { "D1D2CA", "Celeste" },
            new[] { "D1D2DD", "Mischka" },
            new[] { "D1E231", "Pear" },
            new[] { "D2691E", "Hot Cinnamon" },
            new[] { "D27D46", "Raw Sienna" },
            new[] { "D29EAA", "Careys Pink" },
            new[] { "D2B48C", "Tan" },
            new[] { "D2DA97", "Deco" },
            new[] { "D2F6DE", "Blue Romance" },
            new[] { "D2F8B0", "Gossip" },
            new[] { "D3CBBA", "Sisal" },
            new[] { "D3CDC5", "Swirl" },
            new[] { "D47494", "Charm" },
            new[] { "D4B6AF", "Clam Shell" },
            new[] { "D4BF8D", "Straw" },
            new[] { "D4C4A8", "Akaroa" },
            new[] { "D4CD16", "Bird Flower" },
            new[] { "D4D7D9", "Iron" },
            new[] { "D4DFE2", "Geyser" },
            new[] { "D4E2FC", "Hawkes Blue" },
            new[] { "D54600", "Grenadier" },
            new[] { "D591A4", "Can Can" },
            new[] { "D59A6F", "Whiskey" },
            new[] { "D5D195", "Winter Hazel" },
            new[] { "D5F6E3", "Granny Apple" },
            new[] { "D69188", "My Pink" },
            new[] { "D6C562", "Tacha" },
            new[] { "D6CEF6", "Moon Raker" },
            new[] { "D6D6D1", "Quill Gray" },
            new[] { "D6FFDB", "Snowy Mint" },
            new[] { "D7837F", "New York Pink" },
            new[] { "D7C498", "Pavlova" },
            new[] { "D7D0FF", "Fog" },
            new[] { "D84437", "Valencia" },
            new[] { "D87C63", "Japonica" },
            new[] { "D8BFD8", "Thistle" },
            new[] { "D8C2D5", "Maverick" },
            new[] { "D8FCFA", "Foam" },
            new[] { "D94972", "Cabaret" },
            new[] { "D99376", "Burning Sand" },
            new[] { "D9B99B", "Cameo" },
            new[] { "D9D6CF", "Timberwolf" },
            new[] { "D9DCC1", "Tana" },
            new[] { "D9E4F5", "Link Water" },
            new[] { "D9F7FF", "Mabel" },
            new[] { "DA3287", "Cerise" },
            new[] { "DA5B38", "Flame Pea" },
            new[] { "DA6304", "Bamboo" },
            new[] { "DA6A41", "Red Damask" },
            new[] { "DA70D6", "Orchid" },
            new[] { "DA8A67", "Copperfield" },
            new[] { "DAA520", "Golden Grass" },
            new[] { "DAECD6", "Zanah" },
            new[] { "DAF4F0", "Iceberg" },
            new[] { "DAFAFF", "Oyster Bay" },
            new[] { "DB5079", "Cranberry" },
            new[] { "DB9690", "Petite Orchid" },
            new[] { "DB995E", "Di Serria" },
            new[] { "DBDBDB", "Alto" },
            new[] { "DBFFF8", "Frosted Mint" },
            new[] { "DC143C", "Crimson" },
            new[] { "DC4333", "Punch" },
            new[] { "DCB20C", "Galliano" },
            new[] { "DCB4BC", "Blossom" },
            new[] { "DCD747", "Wattle" },
            new[] { "DCD9D2", "Westar" },
            new[] { "DCDDCC", "Moon Mist" },
            new[] { "DCEDB4", "Caper" },
            new[] { "DCF0EA", "Swans Down" },
            new[] { "DDD6D5", "Swiss Coffee" },
            new[] { "DDF9F1", "White Ice" },
            new[] { "DE3163", "Cerise Red" },
            new[] { "DE6360", "Roman" },
            new[] { "DEA681", "Tumbleweed" },
            new[] { "DEBA13", "Gold Tips" },
            new[] { "DEC196", "Brandy" },
            new[] { "DECBC6", "Wafer" },
            new[] { "DED4A4", "Sapling" },
            new[] { "DED717", "Barberry" },
            new[] { "DEE5C0", "Beryl Green" },
            new[] { "DEF5FF", "Pattens Blue" },
            new[] { "DF73FF", "Heliotrope" },
            new[] { "DFBE6F", "Apache" },
            new[] { "DFCD6F", "Chenin" },
            new[] { "DFCFDB", "Lola" },
            new[] { "DFECDA", "Willow Brook" },
            new[] { "DFFF00", "Chartreuse Yellow" },
            new[] { "E0B0FF", "Mauve" },
            new[] { "E0B646", "Anzac" },
            new[] { "E0B974", "Harvest Gold" },
            new[] { "E0C095", "Calico" },
            new[] { "E0FFFF", "Baby Blue" },
            new[] { "E16865", "Sunglo" },
            new[] { "E1BC64", "Equator" },
            new[] { "E1C0C8", "Pink Flare" },
            new[] { "E1E6D6", "Periglacial Blue" },
            new[] { "E1EAD4", "Kidnapper" },
            new[] { "E1F6E8", "Tara" },
            new[] { "E25465", "Mandy" },
            new[] { "E2725B", "Terracotta" },
            new[] { "E28913", "Golden Bell" },
            new[] { "E292C0", "Shocking" },
            new[] { "E29418", "Dixie" },
            new[] { "E29CD2", "Light Orchid" },
            new[] { "E2D8ED", "Snuff" },
            new[] { "E2EBED", "Mystic" },
            new[] { "E2F3EC", "Apple Green" },
            new[] { "E30B5C", "Razzmatazz" },
            new[] { "E32636", "Alizarin Crimson" },
            new[] { "E34234", "Cinnabar" },
            new[] { "E3BEBE", "Cavern Pink" },
            new[] { "E3F5E1", "Peppermint" },
            new[] { "E3F988", "Mindaro" },
            new[] { "E47698", "Deep Blush" },
            new[] { "E49B0F", "Gamboge" },
            new[] { "E4C2D5", "Melanie" },
            new[] { "E4CFDE", "Twilight" },
            new[] { "E4D1C0", "Bone" },
            new[] { "E4D422", "Sunflower" },
            new[] { "E4D5B7", "Grain Brown" },
            new[] { "E4D69B", "Zombie" },
            new[] { "E4F6E7", "Frostee" },
            new[] { "E4FFD1", "Snow Flurry" },
            new[] { "E52B50", "Amaranth" },
            new[] { "E5841B", "Zest" },
            new[] { "E5CCC9", "Dust Storm" },
            new[] { "E5D7BD", "Stark White" },
            new[] { "E5D8AF", "Hampton" },
            new[] { "E5E0E1", "Bon Jour" },
            new[] { "E5E5E5", "Mercury" },
            new[] { "E5F9F6", "Polar" },
            new[] { "E64E03", "Trinidad" },
            new[] { "E6BE8A", "Gold Sand" },
            new[] { "E6BEA5", "Cashmere" },
            new[] { "E6D7B9", "Double Spanish White" },
            new[] { "E6E4D4", "Satin Linen" },
            new[] { "E6F2EA", "Harp" },
            new[] { "E6F8F3", "Off Green" },
            new[] { "E6FFE9", "Hint of Green" },
            new[] { "E6FFFF", "Tranquil" },
            new[] { "E77200", "Mango Tango" },
            new[] { "E7730A", "Christine" },
            new[] { "E79F8C", "Tonys Pink" },
            new[] { "E79FC4", "Kobi" },
            new[] { "E7BCB4", "Rose Fog" },
            new[] { "E7BF05", "Corn" },
            new[] { "E7CD8C", "Putty" },
            new[] { "E7ECE6", "Gray Nurse" },
            new[] { "E7F8FF", "Lily White" },
            new[] { "E7FEFF", "Bubbles" },
            new[] { "E89928", "Fire Bush" },
            new[] { "E8B9B3", "Shilo" },
            new[] { "E8E0D5", "Pearl Bush" },
            new[] { "E8EBE0", "Green White" },
            new[] { "E8F1D4", "Chrome White" },
            new[] { "E8F2EB", "Gin" },
            new[] { "E8F5F2", "Aqua Squeeze" },
            new[] { "E96E00", "Clementine" },
            new[] { "E97451", "Burnt Sienna" },
            new[] { "E97C07", "Tahiti Gold" },
            new[] { "E9CECD", "Oyster Pink" },
            new[] { "E9D75A", "Confetti" },
            new[] { "E9E3E3", "Ebb" },
            new[] { "E9F8ED", "Ottoman" },
            new[] { "E9FFFD", "Clear Day" },
            new[] { "EA88A8", "Carissma" },
            new[] { "EAAE69", "Porsche" },
            new[] { "EAB33B", "Tulip Tree" },
            new[] { "EAC674", "Rob Roy" },
            new[] { "EADAB8", "Raffia" },
            new[] { "EAE8D4", "White Rock" },
            new[] { "EAF6EE", "Panache" },
            new[] { "EAF6FF", "Solitude" },
            new[] { "EAF9F5", "Aqua Spring" },
            new[] { "EAFFFE", "Dew" },
            new[] { "EB9373", "Apricot" },
            new[] { "EBC2AF", "Zinnwaldite" },
            new[] { "ECA927", "Fuel Yellow" },
            new[] { "ECC54E", "Ronchi" },
            new[] { "ECC7EE", "French Lilac" },
            new[] { "ECCDB9", "Just Right" },
            new[] { "ECE090", "Wild Rice" },
            new[] { "ECEBBD", "Fall Green" },
            new[] { "ECEBCE", "Aths Special" },
            new[] { "ECF245", "Starship" },
            new[] { "ED0A3F", "Red Ribbon" },
            new[] { "ED7A1C", "Tango" },
            new[] { "ED9121", "Carrot Orange" },
            new[] { "ED989E", "Sea Pink" },
            new[] { "EDB381", "Tacao" },
            new[] { "EDC9AF", "Desert Sand" },
            new[] { "EDCDAB", "Pancho" },
            new[] { "EDDCB1", "Chamois" },
            new[] { "EDEA99", "Primrose" },
            new[] { "EDF5DD", "Frost" },
            new[] { "EDF5F5", "Aqua Haze" },
            new[] { "EDF6FF", "Zumthor" },
            new[] { "EDF9F1", "Narvik" },
            new[] { "EDFC84", "Honeysuckle" },
            new[] { "EE82EE", "Lavender Magenta" },
            new[] { "EEC1BE", "Beauty Bush" },
            new[] { "EED794", "Chalky" },
            new[] { "EED9C4", "Almond" },
            new[] { "EEDC82", "Flax" },
            new[] { "EEDEDA", "Bizarre" },
            new[] { "EEE3AD", "Double Colonial White" },
            new[] { "EEEEE8", "Cararra" },
            new[] { "EEEF78", "Manz" },
            new[] { "EEF0C8", "Tahuna Sands" },
            new[] { "EEF0F3", "Athens Gray" },
            new[] { "EEF3C3", "Tusk" },
            new[] { "EEF4DE", "Loafer" },
            new[] { "EEF6F7", "Catskill White" },
            new[] { "EEFDFF", "Twilight Blue" },
            new[] { "EEFF9A", "Jonquil" },
            new[] { "EEFFE2", "Rice Flower" },
            new[] { "EF863F", "Jaffa" },
            new[] { "EFEFEF", "Gallery" },
            new[] { "EFF2F3", "Porcelain" },
            new[] { "F091A9", "Mauvelous" },
            new[] { "F0D52D", "Golden Dream" },
            new[] { "F0DB7D", "Golden Sand" },
            new[] { "F0DC82", "Buff" },
            new[] { "F0E2EC", "Prim" },
            new[] { "F0E68C", "Khaki" },
            new[] { "F0EEFD", "Selago" },
            new[] { "F0EEFF", "Titan White" },
            new[] { "F0F8FF", "Alice Blue" },
            new[] { "F0FCEA", "Feta" },
            new[] { "F18200", "Gold Drop" },
            new[] { "F19BAB", "Wewak" },
            new[] { "F1E788", "Sahara Sand" },
            new[] { "F1E9D2", "Parchment" },
            new[] { "F1E9FF", "Blue Chalk" },
            new[] { "F1EEC1", "Mint Julep" },
            new[] { "F1F1F1", "Seashell" },
            new[] { "F1F7F2", "Saltpan" },
            new[] { "F1FFAD", "Tidal" },
            new[] { "F1FFC8", "Chiffon" },
            new[] { "F2552A", "Flamingo" },
            new[] { "F28500", "Tangerine" },
            new[] { "F2C3B2", "Mandys Pink" },
            new[] { "F2F2F2", "Concrete" },
            new[] { "F2FAFA", "Black Squeeze" },
            new[] { "F34723", "Pomegranate" },
            new[] { "F3AD16", "Buttercup" },
            new[] { "F3D69D", "New Orleans" },
            new[] { "F3D9DF", "Vanilla Ice" },
            new[] { "F3E7BB", "Sidecar" },
            new[] { "F3E9E5", "Dawn Pink" },
            new[] { "F3EDCF", "Wheatfield" },
            new[] { "F3FB62", "Canary" },
            new[] { "F3FBD4", "Orinoco" },
            new[] { "F3FFD8", "Carla" },
            new[] { "F400A1", "Hollywood Cerise" },
            new[] { "F4A460", "Sandy brown" },
            new[] { "F4C430", "Saffron" },
            new[] { "F4D81C", "Ripe Lemon" },
            new[] { "F4EBD3", "Janna" },
            new[] { "F4F2EE", "Pampas" },
            new[] { "F4F4F4", "Wild Sand" },
            new[] { "F4F8FF", "Zircon" },
            new[] { "F57584", "Froly" },
            new[] { "F5C85C", "Cream Can" },
            new[] { "F5C999", "Manhattan" },
            new[] { "F5D5A0", "Maize" },
            new[] { "F5DEB3", "Wheat" },
            new[] { "F5E7A2", "Sandwisp" },
            new[] { "F5E7E2", "Pot Pourri" },
            new[] { "F5E9D3", "Albescent White" },
            new[] { "F5EDEF", "Soft Peach" },
            new[] { "F5F3E5", "Ecru White" },
            new[] { "F5F5DC", "Beige" },
            new[] { "F5FB3D", "Golden Fizz" },
            new[] { "F5FFBE", "Australian Mint" },
            new[] { "F64A8A", "French Rose" },
            new[] { "F653A6", "Brilliant Rose" },
            new[] { "F6A4C9", "Illusion" },
            new[] { "F6F0E6", "Merino" },
            new[] { "F6F7F7", "Black Haze" },
            new[] { "F6FFDC", "Spring Sun" },
            new[] { "F7468A", "Violet Red" },
            new[] { "F77703", "Chilean Fire" },
            new[] { "F77FBE", "Persian Pink" },
            new[] { "F7B668", "Rajah" },
            new[] { "F7C8DA", "Azalea" },
            new[] { "F7DBE6", "We Peep" },
            new[] { "F7F2E1", "Quarter Spanish White" },
            new[] { "F7F5FA", "Whisper" },
            new[] { "F7FAF7", "Snow Drift" },
            new[] { "F8B853", "Casablanca" },
            new[] { "F8C3DF", "Chantilly" },
            new[] { "F8D9E9", "Cherub" },
            new[] { "F8DB9D", "Marzipan" },
            new[] { "F8DD5C", "Energy Yellow" },
            new[] { "F8E4BF", "Givry" },
            new[] { "F8F0E8", "White Linen" },
            new[] { "F8F4FF", "Magnolia" },
            new[] { "F8F6F1", "Spring Wood" },
            new[] { "F8F7DC", "Coconut Cream" },
            new[] { "F8F7FC", "White Lilac" },
            new[] { "F8F8F7", "Desert Storm" },
            new[] { "F8F99C", "Texas" },
            new[] { "F8FACD", "Corn Field" },
            new[] { "F8FDD3", "Mimosa" },
            new[] { "F95A61", "Carnation" },
            new[] { "F9BF58", "Saffron Mango" },
            new[] { "F9E0ED", "Carousel Pink" },
            new[] { "F9E4BC", "Dairy Cream" },
            new[] { "F9E663", "Portica" },
            new[] { "F9EAF3", "Amour" },
            new[] { "F9F8E4", "Rum Swizzle" },
            new[] { "F9FF8B", "Dolly" },
            new[] { "F9FFF6", "Sugar Cane" },
            new[] { "FA7814", "Ecstasy" },
            new[] { "FA9D5A", "Tan Hide" },
            new[] { "FAD3A2", "Corvette" },
            new[] { "FADFAD", "Peach Yellow" },
            new[] { "FAE600", "Turbo" },
            new[] { "FAEAB9", "Astra" },
            new[] { "FAECCC", "Champagne" },
            new[] { "FAF0E6", "Linen" },
            new[] { "FAF3F0", "Fantasy" },
            new[] { "FAF7D6", "Citrine White" },
            new[] { "FAFAFA", "Alabaster" },
            new[] { "FAFDE4", "Hint of Yellow" },
            new[] { "FAFFA4", "Milan" },
            new[] { "FB607F", "Brink Pink" },
            new[] { "FB8989", "Geraldine" },
            new[] { "FBA0E3", "Lavender Rose" },
            new[] { "FBA129", "Sea Buckthorn" },
            new[] { "FBAC13", "Sun" },
            new[] { "FBAED2", "Lavender Pink" },
            new[] { "FBB2A3", "Rose Bud" },
            new[] { "FBBEDA", "Cupid" },
            new[] { "FBCCE7", "Classic Rose" },
            new[] { "FBCEB1", "Apricot Peach" },
            new[] { "FBE7B2", "Banana Mania" },
            new[] { "FBE870", "Marigold Yellow" },
            new[] { "FBE96C", "Festival" },
            new[] { "FBEA8C", "Sweet Corn" },
            new[] { "FBEC5D", "Candy Corn" },
            new[] { "FBF9F9", "Hint of Red" },
            new[] { "FBFFBA", "Shalimar" },
            new[] { "FC0FC0", "Shocking Pink" },
            new[] { "FC80A5", "Tickle Me Pink" },
            new[] { "FC9C1D", "Tree Poppy" },
            new[] { "FCC01E", "Lightning Yellow" },
            new[] { "FCD667", "Goldenrod" },
            new[] { "FCD917", "Candlelight" },
            new[] { "FCDA98", "Cherokee" },
            new[] { "FCF4D0", "Double Pearl Lusta" },
            new[] { "FCF4DC", "Pearl Lusta" },
            new[] { "FCF8F7", "Vista White" },
            new[] { "FCFBF3", "Bianca" },
            new[] { "FCFEDA", "Moon Glow" },
            new[] { "FCFFE7", "China Ivory" },
            new[] { "FCFFF9", "Ceramic" },
            new[] { "FD0E35", "Torch Red" },
            new[] { "FD5B78", "Wild Watermelon" },
            new[] { "FD7B33", "Crusta" },
            new[] { "FD7C07", "Sorbus" },
            new[] { "FD9FA2", "Sweet Pink" },
            new[] { "FDD5B1", "Light Apricot" },
            new[] { "FDD7E4", "Pig Pink" },
            new[] { "FDE1DC", "Cinderella" },
            new[] { "FDE295", "Golden Glow" },
            new[] { "FDE910", "Lemon" },
            new[] { "FDF5E6", "Old Lace" },
            new[] { "FDF6D3", "Half Colonial White" },
            new[] { "FDF7AD", "Drover" },
            new[] { "FDFEB8", "Pale Prim" },
            new[] { "FDFFD5", "Cumulus" },
            new[] { "FE28A2", "Persian Rose" },
            new[] { "FE4C40", "Sunset Orange" },
            new[] { "FE6F5E", "Bittersweet" },
            new[] { "FE9D04", "California" },
            new[] { "FEA904", "Yellow Sea" },
            new[] { "FEBAAD", "Melon" },
            new[] { "FED33C", "Bright Sun" },
            new[] { "FED85D", "Dandelion" },
            new[] { "FEDB8D", "Salomie" },
            new[] { "FEE5AC", "Cape Honey" },
            new[] { "FEEBF3", "Remy" },
            new[] { "FEEFCE", "Oasis" },
            new[] { "FEF0EC", "Bridesmaid" },
            new[] { "FEF2C7", "Beeswax" },
            new[] { "FEF3D8", "Bleach White" },
            new[] { "FEF4CC", "Pipi" },
            new[] { "FEF4DB", "Half Spanish White" },
            new[] { "FEF4F8", "Wisp Pink" },
            new[] { "FEF5F1", "Provincial Pink" },
            new[] { "FEF7DE", "Half Dutch White" },
            new[] { "FEF8E2", "Solitaire" },
            new[] { "FEF8FF", "White Pointer" },
            new[] { "FEF9E3", "Off Yellow" },
            new[] { "FEFCED", "Orange White" },
            new[] { "FF0000", "Red" },
            new[] { "FF007F", "Rose" },
            new[] { "FF00CC", "Purple Pizzazz" },
            new[] { "FF00FF", "Magenta / Fuchsia" },
            new[] { "FF2400", "Scarlet" },
            new[] { "FF3399", "Wild Strawberry" },
            new[] { "FF33CC", "Razzle Dazzle Rose" },
            new[] { "FF355E", "Radical Red" },
            new[] { "FF3F34", "Red Orange" },
            new[] { "FF4040", "Coral Red" },
            new[] { "FF4D00", "Vermilion" },
            new[] { "FF4F00", "International Orange" },
            new[] { "FF6037", "Outrageous Orange" },
            new[] { "FF6600", "Blaze Orange" },
            new[] { "FF66FF", "Pink Flamingo" },
            new[] { "FF681F", "Orange" },
            new[] { "FF69B4", "Hot Pink" },
            new[] { "FF6B53", "Persimmon" },
            new[] { "FF6FFF", "Blush Pink" },
            new[] { "FF7034", "Burning Orange" },
            new[] { "FF7518", "Pumpkin" },
            new[] { "FF7D07", "Flamenco" },
            new[] { "FF7F00", "Flush Orange" },
            new[] { "FF7F50", "Coral" },
            new[] { "FF8C69", "Salmon" },
            new[] { "FF9000", "Pizazz" },
            new[] { "FF910F", "West Side" },
            new[] { "FF91A4", "Pink Salmon" },
            new[] { "FF9933", "Neon Carrot" },
            new[] { "FF9966", "Atomic Tangerine" },
            new[] { "FF9980", "Vivid Tangerine" },
            new[] { "FF9E2C", "Sunshade" },
            new[] { "FFA000", "Orange Peel" },
            new[] { "FFA194", "Mona Lisa" },
            new[] { "FFA500", "Web Orange" },
            new[] { "FFA6C9", "Carnation Pink" },
            new[] { "FFAB81", "Hit Pink" },
            new[] { "FFAE42", "Yellow Orange" },
            new[] { "FFB0AC", "Cornflower Lilac" },
            new[] { "FFB1B3", "Sundown" },
            new[] { "FFB31F", "My Sin" },
            new[] { "FFB555", "Texas Rose" },
            new[] { "FFB7D5", "Cotton Candy" },
            new[] { "FFB97B", "Macaroni and Cheese" },
            new[] { "FFBA00", "Selective Yellow" },
            new[] { "FFBD5F", "Koromiko" },
            new[] { "FFBF00", "Amber" },
            new[] { "FFC0A8", "Wax Flower" },
            new[] { "FFC0CB", "Pink" },
            new[] { "FFC3C0", "Your Pink" },
            new[] { "FFC901", "Supernova" },
            new[] { "FFCBA4", "Flesh" },
            new[] { "FFCC33", "Sunglow" },
            new[] { "FFCC5C", "Golden Tainoi" },
            new[] { "FFCC99", "Peach Orange" },
            new[] { "FFCD8C", "Chardonnay" },
            new[] { "FFD1DC", "Pastel Pink" },
            new[] { "FFD2B7", "Romantic" },
            new[] { "FFD38C", "Grandis" },
            new[] { "FFD700", "Gold" },
            new[] { "FFD800", "School bus Yellow" },
            new[] { "FFD8D9", "Cosmos" },
            new[] { "FFDB58", "Mustard" },
            new[] { "FFDCD6", "Peach Schnapps" },
            new[] { "FFDDAF", "Caramel" },
            new[] { "FFDDCD", "Tuft Bush" },
            new[] { "FFDDCF", "Watusi" },
            new[] { "FFDDF4", "Pink Lace" },
            new[] { "FFDEAD", "Navajo White" },
            new[] { "FFDEB3", "Frangipani" },
            new[] { "FFE1DF", "Pippin" },
            new[] { "FFE1F2", "Pale Rose" },
            new[] { "FFE2C5", "Negroni" },
            new[] { "FFE5A0", "Cream Brulee" },
            new[] { "FFE5B4", "Peach" },
            new[] { "FFE6C7", "Tequila" },
            new[] { "FFE772", "Kournikova" },
            new[] { "FFEAC8", "Sandy Beach" },
            new[] { "FFEAD4", "Karry" },
            new[] { "FFEC13", "Broom" },
            new[] { "FFEDBC", "Colonial White" },
            new[] { "FFEED8", "Derby" },
            new[] { "FFEFA1", "Vis Vis" },
            new[] { "FFEFC1", "Egg White" },
            new[] { "FFEFD5", "Papaya Whip" },
            new[] { "FFEFEC", "Fair Pink" },
            new[] { "FFF0DB", "Peach Cream" },
            new[] { "FFF0F5", "Lavender blush" },
            new[] { "FFF14F", "Gorse" },
            new[] { "FFF1B5", "Buttermilk" },
            new[] { "FFF1D8", "Pink Lady" },
            new[] { "FFF1EE", "Forget Me Not" },
            new[] { "FFF1F9", "Tutu" },
            new[] { "FFF39D", "Picasso" },
            new[] { "FFF3F1", "Chardon" },
            new[] { "FFF46E", "Paris Daisy" },
            new[] { "FFF4CE", "Barley White" },
            new[] { "FFF4DD", "Egg Sour" },
            new[] { "FFF4E0", "Sazerac" },
            new[] { "FFF4E8", "Serenade" },
            new[] { "FFF4F3", "Chablis" },
            new[] { "FFF5EE", "Seashell Peach" },
            new[] { "FFF5F3", "Sauvignon" },
            new[] { "FFF6D4", "Milk Punch" },
            new[] { "FFF6DF", "Varden" },
            new[] { "FFF6F5", "Rose White" },
            new[] { "FFF8D1", "Baja White" },
            new[] { "FFF9E2", "Gin Fizz" },
            new[] { "FFF9E6", "Early Dawn" },
            new[] { "FFFACD", "Lemon Chiffon" },
            new[] { "FFFAF4", "Bridal Heath" },
            new[] { "FFFBDC", "Scotch Mist" },
            new[] { "FFFBF9", "Soapstone" },
            new[] { "FFFC99", "Witch Haze" },
            new[] { "FFFCEA", "Buttery White" },
            new[] { "FFFCEE", "Island Spice" },
            new[] { "FFFDD0", "Cream" },
            new[] { "FFFDE6", "Chilean Heath" },
            new[] { "FFFDE8", "Travertine" },
            new[] { "FFFDF3", "Orchid White" },
            new[] { "FFFDF4", "Quarter Pearl Lusta" },
            new[] { "FFFEE1", "Half and Half" },
            new[] { "FFFEEC", "Apricot White" },
            new[] { "FFFEF0", "Rice Cake" },
            new[] { "FFFEF6", "Black White" },
            new[] { "FFFEFD", "Romance" },
            new[] { "FFFF00", "Yellow" },
            new[] { "FFFF66", "Laser Lemon" },
            new[] { "FFFF99", "Pale Canary" },
            new[] { "FFFFB4", "Portafino" },
            new[] { "FFFFF0", "Ivory" },
            new[] { "FFFFFF", "White" }
        };
#endif
    }
}